Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/shared/home/liam.berrisford/GPU_Training/content/game_of_life.py", line 155, in run_life_cupy
    history = simulate_life_cupy(args.size, args.timesteps, record_history=record)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/home/liam.berrisford/GPU_Training/content/game_of_life.py", line 80, in simulate_life_cupy
    grid_gpu = life_step_gpu(grid_gpu)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/home/liam.berrisford/GPU_Training/content/game_of_life.py", line 30, in life_step_gpu
    cp.roll(cp.roll(grid, 1, axis=0), -1, axis=1) +
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/home/liam.berrisford/.cache/pypoetry/virtualenvs/gpu_training_course-WCYLb1XO-py3.12/lib/python3.12/site-packages/cupy/_manipulation/rearrange.py", line 140, in roll
    result = cupy.empty_like(a)
             ^^^^^^^^^^^^^^^^^^
  File "/shared/home/liam.berrisford/.cache/pypoetry/virtualenvs/gpu_training_course-WCYLb1XO-py3.12/lib/python3.12/site-packages/cupy/_creation/basic.py", line 106, in empty_like
    return cupy.ndarray(shape, dtype, memptr, strides, order)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy/_core/core.pyx", line 151, in cupy._core.core.ndarray.__new__
  File "cupy/_core/core.pyx", line 239, in cupy._core.core._ndarray_base._init
  File "cupy/cuda/memory.pyx", line 738, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1424, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1445, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1116, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1137, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 1382, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
  File "cupy/cuda/memory.pyx", line 1385, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 28,800,000,000 bytes (allocated so far: 86,400,000,000 bytes).
Traceback (most recent call last):
  File "/shared/home/liam.berrisford/GPU_Training/slurm_submission_scripts/../content/game_of_life_experiment.py", line 123, in <module>
    subprocess.run(cmd, check=True)
  File "/shared/home/liam.berrisford/spack/opt/spack/linux-zen2/python-3.12.9-aovth3o77v3iw4v6o4z4aphm2co3pven/lib/python3.12/subprocess.py", line 573, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['poetry', 'run', 'game_of_life_gpu', '--size', '60000', '--timesteps', '100']' returned non-zero exit status 1.
